[services.backend]
rootDirectory = "backend"
watchPaths = ["backend/**"]
buildCommand = "yarn install --frozen-lockfile && yarn build"
startCommand = "yarn start:prod"
# healthcheckPath = "/api/health"

[services.frontend]
rootDirectory = "frontend"
watchPaths = ["frontend/**"]
buildCommand = "yarn install --frozen-lockfile && yarn build"
startCommand = "yarn start"
